### ISSUE TITLE
broccoli-persistent-filter:babel random error in windows

### ISSUE THREAD

**Issue by Kilowhisky** [broccolijs/broccoli-persistent-filter#206]
In my ember project in windows i keep getting random instances of the error on build or rebuild of my project. This usually goes away if i edit a file and cause a rebuilt to trigger. Its been happening for a bit of time now but since there has always been a workaround of just forcing a rebuild i've been ignoring it. 

Its now preventing me from packaging due to the high chance of failure.  I'm not sure if this bug should be filed under babel or not. 

```
C:\Users\kilowhisky\Documents\Projects\GIT\my-app>ember s
Build Error (broccoli-persistent-filter:Babel > [Babel: my-app]) in my-app/adapters/group.js

ENOENT: no such file or directory, unlink 'C:\Users\kilowhisky\AppData\Local\Temp\canLinkSrc.tmp'


Stack Trace and Error Report: C:\Users\kilowhisky\AppData\Local\Temp/error.dump.102f63637f6c1fe89b6b92e2672c11a5.log
```

Here is the dump from the log.
```
=================================================================================

ENV Summary:

  TIME: Tue Sep 15 2020 07:49:14 GMT-0700 (Pacific Daylight Time)
  TITLE: ember
  ARGV:
  - C:\Program Files\nodejs\node.exe
  - C:\Users\kilowhisky\AppData\Roaming\npm\node_modules\ember-cli\bin\ember
  - s
  EXEC_PATH: C:\Program Files\nodejs\node.exe
  TMPDIR: C:\Users\kilowhisky\AppData\Local\Temp
  SHELL: null
  PATH:
  - C
  - \Python38\Scripts\;C
  - \Python38\;C
  - \Python27\;C
  - \Python27\Scripts;C
  - \WINDOWS\system32;C
  - \WINDOWS;C
  - \WINDOWS\System32\Wbem;C
  - \WINDOWS\System32\WindowsPowerShell\v1.0\;C
  - \WINDOWS\System32\OpenSSH\;C
  - \Program Files\Microsoft SQL Server\130\Tools\Binn\;C
  - \Program Files\dotnet\;C
  - \ProgramData\chocolatey\bin;C
  - \Program Files\nodejs\;C
  - \Program Files\TortoiseSVN\bin;C
  - \Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C
  - \Program Files\Android\jdk\microsoft_dist_openjdk_1.8.0.25\bin;C
  - \Gradle\gradle-6.6\bin;C
  - \Program Files\TortoiseGit\bin;C
  - \Program Files\Git\cmd;C
  - \Users\kilowhisky\AppData\Local\Microsoft\WindowsApps;C
  - \Users\kilowhisky\.dotnet\tools;C
  - \Users\kilowhisky\AppData\Local\Programs\Microsoft VS Code\bin;C
  - \Users\kilowhisky\AppData\Local\Programs\Fiddler;C
  - \Users\kilowhisky\AppData\Local\atom\bin;C
  - \Users\kilowhisky\AppData\Local\Microsoft\WindowsApps;C
  - \Users\kilowhisky\AppData\Roaming\npm;C
  - \Users\kilowhisky\.dotnet\tools
  PLATFORM: win32 x64
  FREEMEM: 2919727104
  TOTALMEM: 12623286272
  UPTIME: 3889
  LOADAVG: 0,0,0
  CPUS:
  - Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz - 3492
  - Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz - 3492
  - Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz - 3492
  - Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz - 3492
  - Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz - 3492
  - Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz - 3492
  - Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz - 3492
  - Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz - 3492
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.16.0
  - brotli: 1.0.7
  - cldr: 37.0
  - http_parser: 2.9.3
  - icu: 67.1
  - llhttp: 2.0.4
  - modules: 72
  - napi: 6
  - nghttp2: 1.41.0
  - node: 12.18.2
  - openssl: 1.1.1g
  - tz: 2019c
  - unicode: 13.0
  - uv: 1.38.0
  - v8: 7.8.279.23-node.39
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: Error: ENOENT: no such file or directory, unlink 'C:\Users\kilowhisky\AppData\Local\Temp\canLinkSrc.tmp'
    at Object.unlinkSync (fs.js:1129:3)
    at testCanSymlink (C:\Users\kilowhisky\Documents\Projects\GIT\myapp\node_modules\symlink-or-copy\index.js:30:8)
    at Object.<anonymous> (C:\Users\kilowhisky\Documents\Projects\GIT\myapp\node_modules\symlink-or-copy\index.js:9:15)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\kilowhisky\Documents\Projects\GIT\myapp\node_modules\ember-cli-template-lint\node_modules\broccoli-persistent-filter\index.js:12:27)
  - code: [undefined]
  - codeFrame: ENOENT: no such file or directory, unlink 'C:\Users\kilowhisky\AppData\Local\Temp\canLinkSrc.tmp'
  - errorMessage: my-app/adapters/group.js: ENOENT: no such file or directory, unlink 'C:\Users\kilowhisky\AppData\Local\Temp\canLinkSrc.tmp'
        in C:\Users\kilowhisky\AppData\Local\Temp\broccoli-160885nW6RjhVOLSa\out-620-analyzer_ember_auto_import_analyzer
        at broccoli-persistent-filter:Babel > [Babel: my-app] (Babel: my-app)
  - errorType: Build Error
  - location:
    - column: [undefined]
    - file: my-app/adapters/group.js
    - line: [undefined]
    - treeDir: C:\Users\kilowhisky\AppData\Local\Temp\broccoli-160885nW6RjhVOLSa\out-620-analyzer_ember_auto_import_analyzer
  - message: my-app/adapters/group.js: ENOENT: no such file or directory, unlink 'C:\Users\kilowhisky\AppData\Local\Temp\canLinkSrc.tmp'
        in C:\Users\kilowhisky\AppData\Local\Temp\broccoli-160885nW6RjhVOLSa\out-620-analyzer_ember_auto_import_analyzer
        at broccoli-persistent-filter:Babel > [Babel: my-app] (Babel: my-app)
  - name: Error
  - nodeAnnotation: Babel: my-app
  - nodeName: broccoli-persistent-filter:Babel > [Babel: my-app]
  - originalErrorMessage: ENOENT: no such file or directory, unlink 'C:\Users\kilowhisky\AppData\Local\Temp\canLinkSrc.tmp'
  - stack: Error: ENOENT: no such file or directory, unlink 'C:\Users\kilowhisky\AppData\Local\Temp\canLinkSrc.tmp'
    at Object.unlinkSync (fs.js:1129:3)
    at testCanSymlink (C:\Users\kilowhisky\Documents\Projects\GIT\myapp\node_modules\symlink-or-copy\index.js:30:8)
    at Object.<anonymous> (C:\Users\kilowhisky\Documents\Projects\GIT\myapp\node_modules\symlink-or-copy\index.js:9:15)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\kilowhisky\Documents\Projects\GIT\myapp\node_modules\ember-cli-template-lint\node_modules\broccoli-persistent-filter\index.js:12:27)

=================================================================================

```

Here are my dependencies
```
"devDependencies": {
    "@ember-intl/cp-validations": "^4.0.1",
    "@ember/jquery": "^1.1.0",
    "@ember/optional-features": "^2.0.0",
    "@glimmer/component": "^1.0.1",
    "@glimmer/tracking": "^1.0.1",
    "babel-eslint": "^10.1.0",
    "babel-plugin-transform-async-to-generator": "^6.24.1",
    "babel-preset-env": "^1.7.0",
    "babel-preset-react": "^6.24.1",
    "bootstrap-sass": "^3.4.1",
    "bootstrap-tokenfield": "^0.12.0",
    "broccoli-asset-rev": "^3.0.0",
    "corber": "^1.4.2",
    "core-js": "^3.6.5",
    "devtron": "^1.4.0",
    "electron-forge": "^5.2.4",
    "electron-prebuilt-compile": "8.2.0",
    "ember-ajax": "^5.0.0",
    "ember-attacher": "^1.1.1",
    "ember-auto-import": "^1.6.0",
    "ember-basic-dropdown": "^3.0.10",
    "ember-cli": "^3.21.2",
    "ember-cli-active-link-wrapper": "0.5.0",
    "ember-cli-app-version": "^3.2.0",
    "ember-cli-autoprefixer": "^1.0.2",
    "ember-cli-babel": "7.22.1",
    "ember-cli-chart": "^3.7.2",
    "ember-cli-content-security-policy": "^2.0.0-1",
    "ember-cli-dependency-checker": "^3.2.0",
    "ember-cli-document-title-northm": "^1.0.2",
    "ember-cli-google-analytics": "1.5.0",
    "ember-cli-htmlbars": "5.3.1",
    "ember-cli-inject-live-reload": "^2.0.2",
    "ember-cli-moment-shim": "3.8.0",
    "ember-cli-notifications": "^6.3.0",
    "ember-cli-sass": "^10.0.1",
    "ember-cli-shims": "^1.2.0",
    "ember-cli-sri": "^2.1.1",
    "ember-cli-template-lint": "2.0.2",
    "ember-cli-uglify": "^3.0.0",
    "ember-cli-windows": "^2.1.6",
    "ember-colpick": "1.0.0",
    "ember-cordova-events": "^0.1.3",
    "ember-cordova-splash": "^0.1.9",
    "ember-cp-validations": "^4.0.0-beta.9",
    "ember-data": "~3.21.0",
    "ember-data-model-fragments": "5.0.0-beta.0",
    "ember-electron": "^2.10.2",
    "ember-export-application-global": "^2.0.1",
    "ember-fetch": "^8.0.2",
    "ember-flatpickr": "^3.0.1",
    "ember-intl": "^5.5.0",
    "ember-load-initializers": "^2.1.0",
    "ember-local-storage": "^1.7.2",
    "ember-math-helpers": "^2.15.0",
    "ember-maybe-import-regenerator": "^0.1.6",
    "ember-power-select": "^4.0.4",
    "ember-progress-bar": "^1.0.0",
    "ember-qunit": "^4.5.1",
    "ember-radio-button": "^2.0.1",
    "ember-resolver": "8.0.2",
    "ember-route-action-helper": "2.0.8",
    "ember-simple-auth": "^3.0.0",
    "ember-sortable": "^2.1.4",
    "ember-source": "3.20.3",
    "ember-tag-input": "^2.0.1",
    "ember-template-lint": "^2.11.0",
    "ember-truth-helpers": "~2.1.0",
    "ember-wormhole": "^0.5.5",
    "eslint": "^7.8.1",
    "eslint-plugin-ember": "9.0.0",
    "eslint-plugin-node": "11.1.0",
    "font-awesome": "^4.7.0",
    "intl-tel-input": "^17.0.3",
    "ivy-tabs": "4.0.0",
    "loader.js": "^4.7.0",
    "moment": "^2.28.0",
    "moment-timezone": "^0.5.31",
    "node-sass": "^4.14.1",
    "npm-run-all": "^4.1.5",
    "pace-js": "Kilowhisky/pace#master",
    "qrcode": "^1.4.4",
    "qunit-dom": "^1.4.0",
    "sass": "^1.26.10",
    "signalr": "^2.4.1"
  },
```

**Comment by nielsrask** [comment]
I'm experiencing the exact same thing.

`Build Error (broccoli-persistent-filter:Babel > [Babel: dentsure-frontend]) in dentsure-frontend/adapters/application.js

EPERM: operation not permitted, unlink 'C:\Users\n_ras\AppData\Local\Temp\canLinkSrc.tmp'`

`  "devDependencies": {
    "@ember/optional-features": "^2.0.0",
    "base64-js": "^1.3.1",
    "broccoli-asset-rev": "^2.4.5",
    "css-element-queries": "^1.2.3",
    "date-fns": "^2.16.1",
    "ember-ajax": "^3.0.0",
    "ember-auto-import": "^1.11.2",
    "ember-cli": "^3.10.1",
    "ember-cli-app-version": "^3.0.0",
    "ember-cli-babel": "^6.6.0",
    "ember-cli-content-security-policy": "1.1.1",
    "ember-cli-dependency-checker": "^3.1.0",
    "ember-cli-eslint": "^4.2.1",
    "ember-cli-flash": "^1.7.2",
    "ember-cli-htmlbars": "^2.0.1",
    "ember-cli-htmlbars-inline-precompile": "^1.0.0",
    "ember-cli-inject-live-reload": "^1.4.1",
    "ember-cli-new-version": "1.4.4",
    "ember-cli-nouislider": "1.1.0",
    "ember-cli-qunit": "^4.1.1",
    "ember-cli-shims": "^1.2.0",
    "ember-cli-sri": "^2.1.0",
    "ember-cli-template-lint": "^2.0.2",
    "ember-cli-uglify": "^2.0.0",
    "ember-concurrency": "^1.0.0",
    "ember-data": "^3.10.0",
    "ember-electron": "^3.0.0-beta.1",
    "ember-export-application-global": "^2.0.0",
    "ember-g-map": "0.0.25",
    "ember-linkify": "^4.1.2",
    "ember-load": "0.0.17",
    "ember-load-initializers": "^1.0.0",
    "ember-maybe-import-regenerator": "^0.1.6",
    "ember-pickr": "^1.2.3",
    "ember-power-select": "2.3.2",
    "ember-qrcode-shim": "^0.4.0",
    "ember-qunit": "4.4.1",
    "ember-resolver": "^4.0.0",
    "ember-simple-auth": "1.8.2",
    "ember-source": "^3.10.1",
    "ember-uploader": "^2.0.0",
    "ember-user-activity": "1.2.1",
    "ember-wormhole": "^0.6.0",
    "eslint-plugin-ember": "^5.0.0",
    "hotkeys-js": "^3.7.2",
    "install": "0.12.1",
    "loader.js": "^4.2.3",
    "node-emoji": "^1.10.0",
    "pdfjs-dist": "^2.2.228",
    "perfect-scrollbar": "^1.5.0",
    "relevancy": "^0.2.0",
    "three": "^0.118.3"
  },`

**Comment by Kilowhisky** [comment]
So I never ended up fixing this. The only solution was to stop developing in windows and instead use WSL. See instructions at the end of the thread here. https://github.com/ember-cli/ember-cli/issues/7156
